---
benjamin.mueller: bzfmuelb
bergner: ghost
berthold: ghost 
dieter.weninger: weninger
fischer: Fischer
gamrath: bzfgamra
gleixner: bzfpfets
gellermann: ghost
heinz: bzfheinz
hendel: bzfhende
koch: bzfkocht
maher: bzfmaher
michael.winkler: bzfwinkm
miltenberger: bzfmilte
naundorf: ghost
pfetsch: bzfpfets
puchert: puchert
raack: ghost
serrano: bzfserra 
shinano: bzfshina
schwarz: bzfschwa
scipweb: ghost
vigerske: bzfviger 
waniek: ghost
weltge: ghost
witt: witt
witzig: bzfwitzi
wolter: bzfwolte 
